---
plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - bin/*
    - gemfiles/*
    - spec/dummy/**/*
    - benchmarks/*

Gemspec/RequireMFA:
  Enabled: false

#########
# STYLE #
#########

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/ArgumentsForwarding:
  Enabled: false

Style/BlockDelimiters:
  AllowedPatterns: ['expect']

##########
# LAYOUT #
##########

Layout/LineLength:
  Max: 125

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

##########
# NAMING #
##########

Naming/BlockForwarding:
  Enabled: false

#########
# RSPEC #
#########

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

RSpec/ExampleLength:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/MetadataStyle:
  EnforcedStyle: hash

FactoryBot/SyntaxMethods:
  Enabled: false
