development:
  adapter: sqlite3
  database: db/development.sqlite3

test:
  adapter: sqlite3
  # Cannot use ":memory:" because of some weird flaky tests
  # SQLite3::SQLException:
  #   no such table: posts
  database: db/test.sqlite3
