---
name: CI

on:
  - push
  - pull_request

jobs:
  rspec:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.1'
          - '3.0'
          - '2.7'
        rails:
          - rails_6.0.4
          - rails_6.1.5
          - rails_7.0.2

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Setup Ruby cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ matrix.ruby }}-${{ matrix.rails }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-${{ matrix.ruby }}-${{ matrix.rails }}-

      - name: Bundle
        env:
          RAILS_VERSION: ${{ matrix.rails }}
          BUNDLE_GEMFILE: gemfiles/${{ matrix.rails }}.gemfile
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: RSpec
        env:
          RAILS_VERSION: ${{ matrix.rails }}
          BUNDLE_GEMFILE: gemfiles/${{ matrix.rails }}.gemfile
        run: |
          bin/rake
